<?php ?>

<!-- 
NaviBar BlueBlur 
		ver.4.70 
	 Designed and Developed By Sal64dd 
	 contact:sal_uncd@gmail.com 
-->
<div class="gwcol fxd fill txt-noselect digilib_Navibar">
	<!-- Navibar_Layer1 : Layer_Blue -->
	<div class="gwcol abs borderSmooth Navibar_Layer1 Layer_Blue">
	    <div class="gwcol abs siteHeader">
	    	<div class="gwcol abs Digilib_header"></div>
	        <div class="gwcol abs BBPS_header"></div>
	    </div>
	    <div class="gwcol abs aboutUs">
	    	<div class="gwcol image-ab abs border1 PageHeadImage-layer2-2"></div>
	    </div>
	    <div class="gwcol abs copyrightNotice">
	    	<div class="gwcol image abs border1 PageHeadImage-layer2-1">
	    </div>

	    <div class="gwcol abs pg-afull Layer1_bgImage"></div>

	</div>
	<!-- Navibar_Layer2 : Layer_Red -->
	<div class="gwcol abs Navibar_Layer2 Layer_Red">
            <div class="gwcol rel red_content badges"></div>
            <div class="gwcol rel red_content account_settings"></div>
            <div class="gwcol rel red_content notifi"></div>
            <div class="gwcol rel red_content help"></div>
            <div class="gwcol rel red_content profile">
            	<img class="gwcol rel photo"></div>
            	<div class="gwcol rel userid">Username</div>
        	</div>
	</div>
	<!-- Navibar_Layer3 : Layer_Orange -->
	<div class="ggwcol abs border1 borderSmooth Navibar_Layer3 Layer_Orange">
	    <div class="gwcol border1 abs  Navibar-layer3-bgImage borderSmooth"></div>
	    <div class="gwcol border1 abs  Navibar-layer3-content ">
	        <ul class="gwcol abs pg-afull border1 Navibar-layer3-content-ulist NaviContentGroup-ul">
	            <li class="gwcol rel border1 Dynamic Navibar-layer3-content-lelem NaviContentGroup-lelem" onclick="layer2_navi2_click(1)">
	                <div class="NaviContentGroup-lelem-Rllimg Dynamic border1 gwcol rel">
	                    <div class="NaviContentGroup-lelem-img border1 gwcol abs" id="NavCntGrpImg1"></div>
	                </div>
	                <span class="gwcol Navibar-layer3-content-lelem-Navitxt">Home</span>
	                </li>
	            <li class="gwcol rel border1 Dynamic Navibar-layer3-content-lelem NaviContentGroup-lelem"  onclick="layer2_navi2_click(2)">
	                <div class="NaviContentGroup-lelem-Rllimg Dynamic border1 gwcol rel">
	                    <div class="NaviContentGroup-lelem-img border1 gwcol abs" id="NavCntGrpImg2"></div>
	                </div>
	                <span class="gwcol Navibar-layer3-content-lelem-Navitxt">Books</span></li>
	            <div class="gwcol MOBEL MOBEL-naviLinebkr rel border1 Navibar-layer3-content-lelem NaviContentGroup-lelem"></div>
	            <li class="gwcol rel border1   Dynamic Navibar-layer3-content-lelem NaviContentGroup-lelem"  onclick="layer2_navi2_click(3)">
	                <div class="NaviContentGroup-lelem-Rllimg Dynamic border1 gwcol rel">
	                    <div class="NaviContentGroup-lelem-img border1 gwcol abs" id="NavCntGrpImg3"></div>
	                </div>
	                <span class="gwcol Navibar-layer3-content-lelem-Navitxt">StudyZone</span>
	                <div class="NaviContentGroup-lelem-RllDD Dynamic border1 gwcol rel">
	                    <div class="NaviContentGroup-lelem-DDimg border1 gwcol abs" id="NavCntGrpDDImg1"></div>
	                </div>
	                </li>
	            <li class="gwcol rel border1   Dynamic Navibar-layer3-content-lelem NaviContentGroup-lelem"  onclick="layer2_navi2_click(4)">
	                <div class="NaviContentGroup-lelem-Rllimg Dynamic border1 gwcol rel">
	                    <div class="NaviContentGroup-lelem-img border1 gwcol abs" id="NavCntGrpImg4"></div>
	                </div>
	                <span class="gwcol Navibar-layer3-content-lelem-Navitxt">Blogs</span></li>
	            <li class="gwcol rel border1   Dynamic Navibar-layer3-content-lelem NaviContentGroup-lelem"  onclick="layer2_navi2_click(5)">
	                <div class="NaviContentGroup-lelem-Rllimg Dynamic border1 gwcol rel">
	                    <div class="NaviContentGroup-lelem-img border1 gwcol abs" id="NavCntGrpImg5"></div>
	                </div>
	                <span class="gwcol Navibar-layer3-content-lelem-Navitxt">Mics.</span>
	                <div class="NaviContentGroup-lelem-RllDD Dynamic border1 gwcol rel">
	                    <div class="NaviContentGroup-lelem-DDimg border1 gwcol abs" id="NavCntGrpDDImg2"></div>
	                </div>
	                </li>
	        </ul>
	    </div>
	</div>
</div>












